### ISSUE TITLE
segment violation when right-clicking in a cell with an already-answered question

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1373]
I was asked to keep an eye open for regressions introduced by the current improvements. ...and this time I found one:

````
askinteger(i);
````
Now answer the question and right-click on the answer.
````

Thread 1 "wxmaxima" received signal SIGSEGV, Segmentation fault.
0x0000555555772292 in GroupCell::AutoAnswer (this=0x0)
    at /home/gunter/src/wxmaxima/src/cells/GroupCell.h:99
99	  bool AutoAnswer() const { return m_autoAnswer; }
(gdb) backtrace 
#0  0x0000555555772292 in GroupCell::AutoAnswer() const (this=0x0)
    at /home/gunter/src/wxmaxima/src/cells/GroupCell.h:99
#1  0x0000555555744eda in Worksheet::OnMouseRightDown(wxMouseEvent&)
    (this=0x5555563d0880, event=...)
    at /home/gunter/src/wxmaxima/src/Worksheet.cpp:1669
#2  0x00007ffff7369661 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()
    at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#3  0x00007ffff73699fa in wxEvtHandler::SearchDynamicEventTable(wxEvent&) ()
    at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#4  0x00007ffff7369a94 in wxEvtHandler::TryHereOnly(wxEvent&) ()
    at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#5  0x00007ffff7369b4b in wxEvtHandler::ProcessEventLocally(wxEvent&) ()
    at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#6  0x00007ffff7369bf1 in wxEvtHandler::ProcessEvent(wxEvent&) ()
    at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#7  0x00007ffff796b542 in wxScrollHelperEvtHandler::ProcessEvent(wxEvent&) ()
    at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#8  0x00007ffff736997b in wxEvtHandler::SafelyProcessEvent(wxEvent&) ()
    at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#9  0x00007ffff7739f7e in  ()
````
The code handling questions always was fragile, so I guess the reason for the crash might actually lie in some old bug in the old code that has gotten visible only now.

**Comment by gunterkoenigsmann** [comment]
resolved with c08eaf0
