### ISSUE TITLE
wxmaxima allocates huge amount of ram (>40GB) on copying (ctrl-c) a compacted (hidden content) section block

### ISSUE THREAD

**Issue by busomaka** [wxMaxima-developers/wxmaxima#1762]
reproduced on wxmaxima 20.12.1 from Debian Bullseye repos [^1]
reproduced on wxmaxima 23.02.1-DevelopmentSnapshot compiled from github [^2]

To reproduce the issue, open the following a-few-line file

[crash_on_copy.wxmx.zip](https://github.com/wxMaxima-developers/wxmaxima/files/11022886/crash_on_copy.wxmx.zip)

and copy (e.g. with ctrl-c) the section block when compacted.

The wxmaxima process allocates growing amount of memory (more than 40GB, when available), then releases it when done, if not killed with with SIGABRT in the meantime. 

The amount of memory grows with the number of hidden lines.

[^1]: wxWidgets: 3.0.5
Unicode support: yes
Multiprocessing using OpenMP 201511
Using fine-grained OpenMP locks
Maxima version: 5.44.0 (x86_64-pc-linux-gnu)
Maxima compiled using: GNU Common Lisp (GCL) GCL 2.6.12

[^2]:wxWidgets: 3.0.5
Unicode support: yes
Maxima version: 5.44.0 (x86_64-pc-linux-gnu)
Maxima compiled using: GNU Common Lisp (GCL) GCL 2.6.12

**Comment by busomaka** [comment]
I append the output of a gdb session for the 23.02.1-DevelopmentSnapshot on a Linux Devuan Chimaera amd64, if it may be useful.

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

--Type <RET> for more, q to quit, c to continue without paging--
Thread 1 "wxmaxima.curren" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) frame
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	in ../sysdeps/unix/sysv/linux/raise.c
(gdb) where
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6c4d537 in __GI_abort () at abort.c:79
#2  0x00007ffff701c7ec in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7027966 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff70279d1 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7027cb9 in __cxa_rethrow ()
    at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff71d5afc in  () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#7  0x00007ffff78a2b16 in wxMenuBase::SendEvent(int, int) ()
    at /usr/lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#8  0x00007ffff779312f in  ()
    at /usr/lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#9  0x00007ffff624d0a2 in g_closure_invoke ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff625f413 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff62656cf in g_signal_emit_valist ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff6265c3f in g_signal_emit ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff67316b0 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007ffff624d0a2 in g_closure_invoke ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff625f413 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--c
#16 0x00007ffff6265259 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff6265c3f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff64a2d48 in gtk_accel_group_activate () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff64a468d in gtk_accel_groups_activate () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff6754f6e in gtk_window_activate_key () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff7726f7b in  () at /usr/lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#22 0x00007ffff678591b in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#23 0x00007ffff624d0a2 in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff625f413 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff6265259 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007ffff6265c3f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff672fd14 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007ffff65e2ecf in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#29 0x00007ffff65e4a73 in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#30 0x00007ffff62cd785 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#31 0x00007ffff63012e2 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#32 0x00007ffff5fbce6b in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ffff5fbd118 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007ffff5fbd40b in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007ffff65e3a65 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#36 0x00007ffff7714955 in wxGUIEventLoop::DoRun() () at /usr/lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#37 0x00007ffff721897d in wxEventLoopBase::Run() () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#38 0x00007ffff71e19a6 in wxAppConsoleBase::MainLoop() () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#39 0x00005555557ccdf8 in MyApp::OnRun() (this=0x555555d3ff90) at /home/ebertocchi/wxmaxima/src/main.cpp:459
#40 0x00005555557cabd4 in CommonMain() () at /home/ebertocchi/wxmaxima/src/main.cpp:75
#41 0x00005555557cb0b0 in main(int, char**) (argc=1, argv=0x7fffffffdcf8) at /home/ebertocchi/wxmaxima/src/main.cpp:143
```
